version: "3.5"

services:
  cassandra:
    image: cassandra:4.1.3
    ports:
      - "9042:9042"
    networks:
      services-network:
        aliases:
          - cassandra

  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "8080:80"
      - "2003:2003"
      - "8125:8125"
      - "8126:8126"
    networks:
      services-network:
        aliases:
          - statsd

  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
      - "7933:7933"
      - "7833:7833"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "STATSD_ENDPOINT=statsd:8125"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
      - statsd
    networks:
      services-network:
        aliases:
          - cadence

  integ-test-sticky-off:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make integ_test_sticky_off
    environment:
      - "SERVICE_ADDR=cadence:7933"
      - "GO111MODULE=on"
    depends_on:
      - cadence
    volumes:
      - ../../:/go/src/go.uber.org/cadence
    networks:
      services-network:
        aliases:
          - integ-test-sticky-off

  integ-test-sticky-on:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make integ_test_sticky_on
    environment:
      - "SERVICE_ADDR=cadence:7933"
      - "GO111MODULE=on"
    depends_on:
      - cadence
    volumes:
      - ../../:/go/src/go.uber.org/cadence
    networks:
      services-network:
        aliases:
          - integ-test-sticky-on

  integ-test-grpc:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make integ_test_grpc
    environment:
      - "SERVICE_ADDR=cadence:7833"
      - "ENABLE_GRPC_ADAPTER=true"
      - "GO111MODULE=on"
    depends_on:
      - cadence
    volumes:
      - ../../:/go/src/go.uber.org/cadence
    networks:
      services-network:
        aliases:
          - integ-test-grpc

  unit-test:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make unit_test
    environment:
      - "GO111MODULE=on"
    volumes:
      - ../../:/go/src/go.uber.org/cadence
    networks:
      services-network:
        aliases:
          - unit-test

  coverage-report:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - |
        make coverage_report
    environment:
      - "GO111MODULE=on"
    volumes:
      - ../../:/go/src/go.uber.org/cadence

networks:
  services-network:
    name: services-network
    driver: bridge
